### ISSUE TITLE
Allowance of null schema types is inconsistent

### ISSUE THREAD

**Issue by abargnesi** [jsongraph/json-graph-specification#21]
Not all optional properties can be set as a `null` type. This should be consistent for all because I believe the semantics of _null_ equal that of omission.

This is with respect to one of our stated design principles:

`Properties that allow a null value can be omitted.`

We should rewrite it as:

`Optional properties can either be null or omitted.`

Offending properties:
- _graph.label_
- _graph.type_
- _node.label_
- _edge.id_
- _edge.relation_
- _edge.label_

**Comment by wshayes** [comment]
Handled with Version 2 of the JGF schema definition.
