### ISSUE TITLE
Add top-level keyword in graph object for JSONSchema specification

### ISSUE THREAD

**Issue by wshayes** [jsongraph/json-graph-specification#27]
Now that there are standard schema stores on the web (e.g. http://schemastore.org/json/), it makes sense to make the JGF JSON documents self-describing by adding a URI to the JGF (or JGF-subtype) including version.

Example:
```
{
    "graph": {
         "label": "graph1",
         "schema_uri": "http://schemastore.org/json/jgf-3-bel.schema.json",
         ...
    }
...
}

**Comment by adifabio** [comment]
Agreed.  The schema can be self defining this way.  A positive.

**Comment by abargnesi** [comment]
A great idea! A schema version is critical for library authors to conditionally switch parsers.

We may want to check out the work snowplow did on this: SchemaVer and a "self" property.

https://snowplowanalytics.com/blog/2014/05/15/introducing-self-describing-jsons/

**Comment by wshayes** [comment]
That's funny - that's the article that encouraged me to suggest this.
