### ISSUE TITLE
jay-gee-eff: npm client module for manipulating json-graph-specification

### ISSUE THREAD

**Issue by bigman73** [jsongraph/json-graph-specification#28]
Hi,
I really like the JGF spec. It is clean, easy on the eyes, and straightforward to read and write.

So I wrote an npm module as a nodejs client - it is called jay-gee-eff: (MIT license)
https://www.npmjs.com/package/jay-gee-eff

Github: https://github.com/bigman73/jay-gee-eff

I'll create a pull request for the README.md. I'm asking you to kindly add the project to the list of clients

Thanks
Yuval

**Comment by wshayes** [comment]
Added to Readme and http://jsongraphformat.info/ website.  Missed these requests - I hope I've fixed my monitoring of these issue queues.
