### ISSUE TITLE
SRO - renaming

### ISSUE THREAD

**Issue by wshayes** [jsongraph/json-graph-specification#33]
This would be a major version change, but after doing a survey of the graph/network literature, subject, relation, object is more frequently used than source, relation, target. I'd like to add subject, object as aliases with source, target being deprecated (still available but planned for removal).

**Comment by nichtich** [comment]
The *literature* may use different terminology but in other graph *formats* the terms `source` and `target` are also common.

**Comment by wshayes** [comment]
Not worth the disruption given lack of clear community preference. Closing.
