### ISSUE TITLE
JGF direct indexing possibilities

### ISSUE THREAD

**Issue by erik470** [jsongraph/json-graph-specification#39]
# Framing
In a lot of languages JSON can be read and used directly in a data-structure. Most of those languages support direct indexing possibilities. The JGF however does not make use of this advantage at this point.

# Proposal
My proposal consist of extending the specification to allow users to make use of the direct indexing capabilities in program languages.

# Example
For example in Python a JSON gets translated to a dictionary. Python allows constant indexing on the keys in a dictionary. If the JGF could be extended such that the id of the nodes and edges are used as keys, then users could retrieve edges and nodes in constant time in comparison to the linear retrieval which has to happen at this point.

**Comment by wshayes** [comment]
I'm trying to remember why we originally made them arrays instead of dictionaries. I generally prefer dictionaries as they are easy to work with in python. I think it was because dictionaries are not handled well in javascript - but ES2015+ has greatly improved dictionary handling. @abargnesi or @adifabio - what do you remember about that decision?

I'm up for this if we can get general approval. I'd like to update the specification in a few other ways (e.g. and a graph.id field, best practice suggestions, additional standardized but optional metadata)

**Comment by adifabio** [comment]
@wshayes you are correct; it had to do with the fact that arrays were easier to use.  I am also in favor of modernizing the specification as there are some items I would like to see added to it while maintaining the   flexibility and simplicity of the specification.

**Comment by erik470** [comment]
Thank you for quick and positive reactions.

I really like the specification you already designed, thank you for that. As it seems that there could be an update of the specification, I would be happy if I could contribute? This way I could give something back.

**Comment by wshayes** [comment]
That sounds great - can you start a Pull Request and we'll work off of that. We'll work off the develop branch until we are ready to release this as the 2.0 version.

Thanks for proposing this.

**Comment by wshayes** [comment]
We should probably add a script to convert JGF1.0 to JGF2.0

**Comment by erik470** [comment]
Yes, that is a good idea.  Also, maybe we can compile a list of all aspects we want in the new version. This way we get an overview of what needs to be added or taken into account to.

**Comment by tgig** [comment]
Hey guys, I'm interested in this modernization of the spec as well. Any update on current status? Need help?

**Comment by abargnesi** [comment]
Hi @tgig, @erik470 started PR #40 if you want to contribute.

Looking through the next proposals I see:
- `id` keys (#39)
- `id` field for a graph object (#32)
- schema URI in graph object (#27)
- streaming format (#26)

Streaming could be supported in JGF 2.0, but a separate schema would be appropriate. Not all clients should have to implement streaming read/write.

**Comment by tgig** [comment]
I'll have a shot at it. Give me a few days.

**Comment by wshayes** [comment]
That would be great - work got a little crazy during the holidays - thought I’d have more time but end of the year deadlines hit me hard.
