### ISSUE TITLE
Question: online tools for JGF view

### ISSUE THREAD

**Issue by fanavarro** [jsongraph/json-graph-specification#44]
Hi, I am developing a java library for graph management. One important point is the serialization of graphs, thus I've started by implementing JGF serialization. Nonetheless, I've seen that there is a lack of resources for JGF visualization.

The unique app for final users I've found is cytoscape with the JGF-app plugin. Since I'm currently learning how JGF works, I find this app a little bit time consuming because I am playing with the  JGF plain text file, so I have to open it in my text editor, modify it, save it, and open it through cytoscape in order to see how the changes I made in the text file are interpreted when drawing the graph.

My question is: are there other final applications that let the user to see the plain JGF file together with the resulting graph, allowing the modification of the JGF file?

Thanks before hand.
Francisco Abad.

**Comment by wshayes** [comment]
Hi Francisco,

The JGF-app is supposed to allow changes to be made and allow saving in JGF. We'd love your help with the Cytoscape plugin if it's not working - don't have anyone on the project that is fluent in Java at the moment.

I'm also part of a company building a tool that creates biological networks and allows imports/exports in JGF - you can go to https://biodati.com and try the demo - we don't yet have direct network visualization editing like in Cytoscape.

**Comment by fanavarro** [comment]
Hi @wshayes, thanks for your answer. Cytoscape is working well. What I was looking for is a simpler application to directly write the JGF and to preview the resulting graph. Cytoscape is a very good application, but I found it quite complex for my objectives (learn and test JGF files) since it supports many graph formats and you only can load JGF through loading files, but you cant modify this file directly in the app. Then, for each little change I made to the graph, I have to open the JGF file with the text editor, make the modification, save it, import it into cytoscape, reorganize the layout and see the resulting graph.

I will take a look to biodati, thanks again for your answer.

Regards!

**Comment by wshayes** [comment]
Maybe this then? https://github.com/jsongraph/jsongraph.d3 <https://github.com/jsongraph/jsongraph.d3>

**Comment by fanavarro** [comment]
Hi again @wshayes, thanks for your reply!

I've tried the project jsongraph.d3, but it only shows an example graph. Maybe I can develop an app reusing that with two components: a textbox to write json, and a a div to render the graph.

I'll post it here when I get it.
